services:
  mna-sycl-dev:
    image: luizfxavier/mna-sycl-dev:0.1
    build:
      context: .
      dockerfile: Dockerfile

    working_dir: /app/src

    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
                - nvidia.com/gpu=all
              capabilities: [gpu]

    environment:
      - DATASET_INPUT=${DATASET_INPUT}
      - NUM_RUNS=${NUM_RUNS}
      - PAR_ALFA=${PAR_ALFA}
      - PAR_BETA=${PAR_BETA}
      - ACPP_TARGETS=generic

    volumes:
      - type: bind
        source: .
        target: /app/src

      - type: bind
        source: inputs/
        target: /app/inputs
      
      - type: bind
        source: ${HOST_OUTPUT_DIR}
        target: /app/output

      - type: volume
        # source: ../out/
        target: /app/out/build/docker-sycl

    command: >
      /bin/bash -c "
        chmod +x /app/src/dev_env.sh
        /app/src/dev_env.sh;      
      "

  mna-cpp-dev:
    image: luizfxavier/mna:1.0
    build:
      context: .
      dockerfile: Dockerfile

    working_dir: /app/src

    volumes:
      - type: bind
        source: .
        target: /app/src

      - type: bind
        source: ../inputs/
        target: /app/inputs
      
      - type: bind
        source: ${HOST_OUTPUT_DIR}
        target: /app/output

      - type: volume
        target: /app/out/build/docker-dev

    command: >
      /bin/bash -c "
      echo '⚙️ Initializing...';
      cmake --preset=docker-dev &&
      cmake --build --preset=docker-dev &&
      /app/out/build/docker-dev/dimna/di_mna
      --in /app/${DATASET_INPUT}
      --out /app/output/
      --runs ${NUM_RUNS}
      --cs ${PAR_ALFA}
      --ccn ${PAR_BETA};
      
      echo '🔭 Watching for changes on /app/src...';
      
      while inotifywait -q -r -e modify,create,delete /app/src
      --exclude 'nohup.out|output|run.py'; do
        echo '🔄 Change detected! Recompiling...';
        cmake --build --preset docker-dev && 
        /app/out/build/docker-dev/dimna/di_mna --in /app/${DATASET_INPUT} --out /app/output/ --runs ${NUM_RUNS} --cs ${PAR_ALFA} --ccn ${PAR_BETA};
        echo '✅ Execution finished. Waiting for changes...';
      done
      "
