# Builder stage

FROM ubuntu:24.04 AS builder
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /build_env

# System dependencies and Python
RUN apt-get update && apt-get install -y \
  software-properties-common git build-essential ninja-build curl zip unzip tar flex bison \
  pkg-config wget inotify-tools clang libclang-dev lld llvm-dev clang-tools libomp-dev python3

RUN ln -s /usr/bin/clang-scan-deps-18 /usr/bin/clang-scan-deps || true

# AMD ROCm & HIP Setup (Builder needs dev libraries)
RUN wget https://repo.radeon.com/amdgpu-install/6.4/ubuntu/noble/amdgpu-install_6.4.60400-1_all.deb \
  && apt-get install -y ./amdgpu-install_6.4.60400-1_all.deb \
  && apt-get update \
  && amdgpu-install -y --usecase=hip,hiplibsdk,rocm --no-dkms \
  && rm amdgpu-install_6.4.60400-1_all.deb \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

# Apache Arrow
RUN wget https://apache.jfrog.io/artifactory/arrow/ubuntu/apache-arrow-apt-source-latest-noble.deb \
  && apt-get install -y ./apache-arrow-apt-source-latest-noble.deb \
  && apt-get update \
  && apt-get install -y libarrow-dev libparquet-dev libarrow-dataset-dev \
  && rm apache-arrow-apt-source-latest-noble.deb \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

# CMake
ARG CMAKE_VERSION=4.3.1
RUN curl -L "https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-x86_64.tar.gz" -o cmake.tar.gz \
    && tar -xzf cmake.tar.gz -C /usr/local --strip-components=1 && rm cmake.tar.gz

# AdaptiveCpp (ROCm Backend)
RUN git clone --depth 1 https://github.com/AdaptiveCpp/AdaptiveCpp.git /opt/AdaptiveCpp && \
    cd /opt/AdaptiveCpp && mkdir build && cd build && \
    cmake .. -DWITH_ROCM_BACKEND=ON -DCMAKE_INSTALL_PREFIX=/opt/acpp && \
    make -j$(nproc) && make install && \
    rm -rf /opt/AdaptiveCpp

# vcpkg
RUN git clone --depth 1  https://github.com/microsoft/vcpkg.git /opt/vcpkg && /opt/vcpkg/bootstrap-vcpkg.sh
RUN ls
# Project compilation
COPY src/ /build_env/src/
COPY scripts/test_env.sh /build_env/src/test_env.sh 
WORKDIR /build_env/src
# Usage of docker-sycl preset for ACPP setup
RUN chmod +x /build_env/src/test_env.sh &&  /build_env/src/test_env.sh

# =====================================
# Runtime stage

FROM ubuntu:24.04 AS runtime
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app

# Python, runtime libraries, and ROCm runtime
RUN apt-get update && apt-get install -y wget python3 python3-pip libomp5 \
    && wget https://apache.jfrog.io/artifactory/arrow/ubuntu/apache-arrow-apt-source-latest-noble.deb \
    && apt-get install -y ./apache-arrow-apt-source-latest-noble.deb \
    && wget https://repo.radeon.com/amdgpu-install/6.4/ubuntu/noble/amdgpu-install_6.4.60400-1_all.deb \
    && apt-get install -y ./amdgpu-install_6.4.60400-1_all.deb \
    && apt-get update \
    && apt-get install -y libarrow-dev libparquet-dev \
    && amdgpu-install -y --usecase=rocm --no-dkms \
    && rm -rf /var/lib/apt/lists/* *.deb

# executable 
COPY --from=builder /build_env/src/out/build/docker-sycl/dimna_sycl/di_mna_sycl /app/di_mna_sycl
RUN ls
# Python script
COPY scripts/docker_run.py /app/docker_run.py
